version: "3"

services:

  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    ports:
      - "127.0.0.1:8086:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}

  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - influxdb
    depends_on:
      - influxdb

  fediwatcher:
    image: papey/fediwatcher:${FEDIWATCHER_VERSION}
    volumes:
      - ./tests/conf.d:/etc/fediwatcher/conf.d
    environment:
      - INFLUXDB_DATABASE=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_HOST=http://${INFLUXDB_HOST}:8086
    depends_on:
      - influxdb
      - grafana


